# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Никишин Евгений Сергеевич

Группа: 317

### Примечание: так как задание по практикуму будем выполнять на python3, писал все на python3, вследствие чего некоторые элементы вашего кода пришлось изменить

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [1]:
[x for x in range(1, 101) if x % 7 == 0 and x % 5 != 0]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

In [3]:
?str.split

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [2]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [12]:
def sort_tokens(s):
    return ','.join(sorted(s.split(sep=',')))
print(sort_tokens('abc,def,111'))
print(sort_tokens('ночь,фонарь,улица,аптека'))
print(sort_tokens('Это, как видно, предложение, в котором много, как нетрудно видеть, обособлений'))

111,abc,def
аптека,ночь,улица,фонарь
 в котором много, как видно, как нетрудно видеть, обособлений, предложение,Это


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [14]:
def remove_duplicates(a):
    return sorted(list(set(a)))
print(remove_duplicates([u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"] ))

['аптека', 'ночь', 'улица', 'фонарь']


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [24]:
ll = [x for x in map(lambda x: x.split(), [u'ночь улица фонарь аптека', u'аптека улица фонарь'])]

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [35]:
from functools import reduce
reduce(lambda x, y: x + y, ll)

['ночь', 'улица', 'фонарь', 'аптека', 'аптека', 'улица', 'фонарь']

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [37]:
from collections import defaultdict
d = defaultdict(int)
print (d)
d['abc'] += 1
print (d)
d['xxx']
print (d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [44]:
from functools import reduce
from collections import defaultdict

def word_counts(texts):
    l = reduce(lambda x, y: x + y, [x for x in map(lambda x: x.split(), texts)])
    d = defaultdict(int)
    for word in l:
        d[word] += 1
    for key in d.keys():
        print(key, d[key])

word_counts([u'ночь улица фонарь аптека', u'аптека улица фонарь фонарь фонарь', "фонарь"])

аптека 2
ночь 1
улица 2
фонарь 5


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Удалите из него все специальные символы и цифры. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [61]:
#####Очень долго качает, поэтому я скачал сам и положил в одну папку с ноутбуком


#from urllib.request import urlopen
#url = "http://www.gutenberg.org/files/2554/2554.txt"
#response = urlopen(url)
#raw_text = response.read().decode('utf8')
#print(type(raw_text))

raw_text = open("./2554.txt", "r").read()#.decode('utf8')

In [70]:
raw_text[:1100]

"The Project Gutenberg EBook of Crime and Punishment, by Fyodor Dostoevsky\n\nThis eBook is for the use of anyone anywhere at no cost and with\nalmost no restrictions whatsoever.  You may copy it, give it away or\nre-use it under the terms of the Project Gutenberg License included\nwith this eBook or online at www.gutenberg.org\n\n\nTitle: Crime and Punishment\n\nAuthor: Fyodor Dostoevsky\n\nRelease Date: March 28, 2006 [EBook #2554]\n[Last updated: November 15, 2011]\n\nLanguage: English\n\nCharacter set encoding: ASCII\n\n*** START OF THIS PROJECT GUTENBERG EBOOK CRIME AND PUNISHMENT ***\n\n\n\n\nProduced by John Bickers; and Dagny\n\n\n\n\n\nCRIME AND PUNISHMENT\n\nBy Fyodor Dostoevsky\n\n\n\nTranslated By Constance Garnett\n\n\n\n\nTRANSLATOR'S PREFACE\n\nA few words about Dostoevsky himself may help the English reader to\nunderstand his work.\n\nDostoevsky was the son of a doctor. His parents were very hard-working\nand deeply religious people, but so poor that they lived with the

In [71]:
#raw_text = filter(lambda x: len(x) > 0, raw_text)

from functools import reduce
from collections import defaultdict
import re

def word_counts(text):
    text = text.lower()
    text = re.split('\W+', text)
    text = list(filter(lambda x: len(x) > 0, text))
    d = defaultdict(int)
    for word in text:
        d[word] += 1
    lpop = []
    lone = []
    items = list(d.items())
    for i in range(20):
        lpop.append((max(items, key=lambda x: x[1]))[0])
        items.remove(max(items, key=lambda x: x[1]))
        lone.append((min(items, key=lambda x: x[1]))[0])
        items.remove(min(items, key=lambda x: x[1]))
    print ("Список 20 самых популярных слов:", lpop, '\n')
    print ("Список 20 слов, встречающихся 1 раз в тексте:", lone)
        
word_counts(raw_text)

Список 20 самых популярных слов: ['the', 'and', 'to', 'he', 'a', 'i', 'you', 'of', 'it', 'that', 'in', 'was', 'his', 'at', 'her', 'but', 'not', 's', 'with', 'she'] 

Список 20 слов, встречающихся 1 раз в тексте: ['lawgiver', 'uncanny', 'butter', 'streaked', 'raff', 'tenderness', 'emergency', 'bolt', 'silversmith', 'shabbiness', 'uncleanness', 'rays', 'barefooted', 'remarking', 'assert', 'staff', 'harmoniously', 'viazemsky', 'provocative', 'compels']


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [69]:
m = np.zeros(1000)
for i in range(1000):
    A, B = np.random.normal(size = (10, 10)), np.random.normal(size = (10, 10))
    m[i] = np.dot(A, B).max()
print(m.sum()/1000)
print(np.percentile(m, 95))

8.4440872453
12.1529962234


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [128]:
a = np.random.poisson(lam=5, size=(10,))
b = np.bincount(a)
b

array([0, 1, 1, 2, 0, 4, 1, 0, 0, 1])

#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [129]:
def f(a):
    return np.repeat(range(len(a)), a)
f(a)

array([0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 9, 9, 9, 9, 9])

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [136]:
def scale(X):
    s = (np.std(X, axis=0) == np.zeros(X.shape[1])) + np.std(X, axis=0)
    return (X - np.mean(X, axis=0)) / s

#Вроде работает
         
A = np.vstack((np.eye(4),[1, 1, 1, 1]))
print(A)
print(scale(A))
print()
print(scale(np.ones((3, 4))))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]
 [ 1.  1.  1.  1.]]
[[ 1.22474487 -0.81649658 -0.81649658 -0.81649658]
 [-0.81649658  1.22474487 -0.81649658 -0.81649658]
 [-0.81649658 -0.81649658  1.22474487 -0.81649658]
 [-0.81649658 -0.81649658 -0.81649658  1.22474487]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [160]:
B = np.random.normal(loc=10, size = (4, 4))
print (B)
print ("det =", np.linalg.det(B))
print ("trace =", np.trace(B))
print ("max =", np.max(B))
print ("min =", np.min(B))
print ("spectral norm =", np.linalg.norm(B, ord=2))
print ("Frobenius norm =", np.linalg.norm(B, ord='fro'))
print ("eigenvalues =", np.linalg.eigvals(B))
print ("inverted")
print (np.linalg.inv(B))

[[  9.77782786   9.38998953  10.89344103   9.65646889]
 [  9.00602992   8.973025     9.47409509  10.01247318]
 [ 10.54662067  11.55145253   9.59912939   9.5385298 ]
 [ 10.13698392   8.97410358   9.48667306  10.37151533]]
det = -54.334893183
trace = 38.7214975815
max = 11.5514525311
min = 8.9730249989
spectral norm = 39.3711657394
Frobenius norm = 39.445867877
eigenvalues = [ 39.35356488+0.j          -1.53598058+0.j           0.45195664+0.83344484j
   0.45195664-0.83344484j]
inverted
[[ 0.14716031 -1.1246997   0.05941076  0.89411094]
 [-0.20396656  0.42470079  0.3273215  -0.52112678]
 [ 0.56338435 -0.02780807 -0.17411922 -0.33756249]
 [-0.48266696  0.75722397 -0.18202267 -0.01779852]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [79]:
#опять очень долго, скачал вручную и положил в папку с ноутбуком

data = pd.read_csv('./2008.csv')

In [99]:
data.CancellationCode[data.CancellationCode.notnull()].value_counts()

B    54904
A    54330
C    28188
D       12
dtype: int64

In [ ]:
df = pd.DataFrame(data)
?df.groupby()