In [49]:
import numpy as np
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
x[(x % 2 == 0) | (x % 2 != 0)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
N = 10000000
a = np.random.rand(N, 2)
a[:10]

array([[ 0.61306086,  0.06616175],
       [ 0.53605848,  0.63673104],
       [ 0.86520322,  0.10226747],
       [ 0.76781878,  0.3062499 ],
       [ 0.80850743,  0.07234322],
       [ 0.98487203,  0.5345476 ],
       [ 0.64111897,  0.42407546],
       [ 0.10735037,  0.30445869],
       [ 0.31183931,  0.9507932 ],
       [ 0.01681995,  0.21337725]])

In [31]:
res = np.sum(a[(a[:, 0] <= 0.5), 1] <= np.cos(a[(a[:, 0] <= 0.5), 0] ** 2)) / N
res

0.4968958

In [33]:
x = np.array([1, 2, np.nan, np.inf, np.inf, np.nan, 5, 4])

In [34]:
np.mean(x[(x == x) & (x != np.inf)])

3.0

In [37]:
H = np.arange(15) ** 0.5
H

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])

In [38]:
Hmax = 3.0
Hmin = 1.5
H[H > Hmax] = Hmax
H[H < Hmin] = Hmin
H

array([ 1.5       ,  1.5       ,  1.5       ,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.        ,  3.        ,  3.        ,  3.        ,  3.        ])

In [46]:
H = np.arange(15) ** 0.5
H

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])

In [47]:
H = np.maximum(H, Hmin)
H

array([ 1.5       ,  1.5       ,  1.5       ,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])

In [48]:
H = np.minimum(H, Hmax)
H

array([ 1.5       ,  1.5       ,  1.5       ,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.        ,  3.        ,  3.        ,  3.        ,  3.        ])

In [66]:
B = np.arange(15)

In [53]:
B.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [67]:
B.shape = 5, 3
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [68]:
B = B.ravel()
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
B = B.reshape(5, 3)
B

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])